// Action Types
export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS';
export const ADD_PERMISSION = 'ADD_PERMISSION';
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';
